### ISSUE TITLE
Monospace

### ISSUE THREAD

**Issue by bioball** [vladaspasic/express-exceptions#3]
Nice library! However, the nitpick in me is unreasonably bothered when I read code that's not in a monospace font. I'd suggest using this font rule for any piece of code, and also the exception message:

``` css
font-family: Monaco, Menlo, monospace
```

**Comment by vladaspasic** [comment]
Hi @bioball, you were right about the font, it looks better now. This is now the only font used on the page.

Check it out, the new version `0.0.7` has been released.

**Comment by bioball** [comment]
Right on.
